### PR TITLE
libhalgal: remove SOVERSION

### PR DESCRIPTION
**Pull request by Informatic**
Version 1 and 2 have equivalent ABI for our usecase.

### CODE REVIEW

**Comment by mariotaku** [comment]
SOVERSION will affect so file suffix. Is it OK to link to `.so` file directly?

**Comment by Informatic** [comment]
Yeah, that's sort of the plan, unless we can make it link against `.so.1` OR `.so.2` (don't think we can?)

vtcapture-based hyperion-webos shipped in current `piccap` works fairly well this way on TVs with `.so.1` and `.so.2`. (as both have `.so` symlink as well) In that case tv-native-apis has never been patched for that, and only now we noticed that, after someone reported a regression...

**Comment by mariotaku** [comment]
OK, sounds fair! Could you add such note there? I think otherwise it should work fine.

**Review by mariotaku — APPROVED** [review]

**Comment by Informatic** [comment]
Sure.

**Comment by mariotaku** [comment]
Please merge anytime when needed :)

**Pull request merged**
